### ISSUE TITLE
Include checksums in releases

### ISSUE THREAD

**Issue by malaire** [getopenmono/openmono_package#5]
For releases include checksums (e.g. SHA256) of files included in release, to allow validation of downloaded files.

This would make it possible for others to mirror the files and still be certain that files have not been modified in any way. (At the moment downloading from github is extremely slow, under 4k/s.)

**Comment by stoffera** [comment]
This could easily be done. Then included either in GitHub release's text or as serarate files in the release.

**Comment by stoffera** [comment]
I imagine that we can use the `shasum` command line util:

```
$ shasum -a 256 PACKAGE_FILE > PACKAGE_FILE.sha256
```
